name: dev
channels:
  - defaults
  - conda-forge
  - http://idshost:5050/dev-skyworks
  - http://idshost:5050/ids-skyworks
dependencies:
  - conda=4.9.2
  - IDS-skill
  # Build
  - sphinx=1.8.*
  - recommonmark=0.6.*
  - sphinx_rtd_theme=0.4.*
  - xonsh